### ISSUE TITLE
update pkgdown docs

### ISSUE THREAD

**Issue by jayhesselberth** [jayhesselberth/widgetdown#3]
If you use htmlwidgets in a Rmarkdown README, you will need to update the front matter to:

```yaml
---
output: github_document
always_allow_html: yes
---
```
